services:
  flask-app:
    build: ./web-app
    container_name: flask_app
    ports:
      - "10000:5000"
    env_file:
      - ./web-app/.env
    depends_on:
      - mongodb
  
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ics-client:
    build: ./ics-client
    container_name: ics_client
    depends_on:
      - mongodb
    env_file:
      - ./ics-client/.env



volumes:
  mongo-data:
  
networks:
  app-network:
    driver: bridge