name: Client CI
on: [push, pull_request]

jobs:
  test-ics-client:
    name: Test ICS Client
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Add MongoDB as a service container
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
          - 27017:27017
        # Health check to wait for MongoDB to be ready
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ics-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pipenv and dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run all tests with pytest
        env:
          MONGO_URI: mongodb://admin:secret@localhost:27017
          MONGO_DBNAME: test_ics_client_db
        run: PYTHONPATH=. pipenv run pytest tests/ -v
