name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Droplet to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 178.128.145.113 >> ~/.ssh/known_hosts

    - name: Execute Deployment Commands on Droplet
      run: |
        ssh root@178.128.145.113 "cd /root/5-final-dot-ics && git pull origin main && docker compose up --build -d"
